branches:
    only:
        - develop
language: python
python:
    - 2.7
before_install:
    - sudo apt-get clean
install:
    - uname -a
    -  df -h
    - sudo add-apt-repository -y ppa:scilifelab/scilifelab
    - sudo add-apt-repository -y ppa:debian-med/ppa
    - sudo apt-get update
    - sudo apt-get install --force-yes git-core gcc snpeff picard-tools bowtie bwa freebayes fastqc-0.10.1 gatk r-base texlive tophat openjdk-6-jre samtools unzip lftp cufflinks wigtools.
    - df -h
    - python deploy_non_root.py install
notifications:
    email: false
script: nosetests