branches:
    only:
        - develop

language: python

python:
    - 2.7

notifications:
    email: false

before_install:
    #Clean up some space
    - sudo apt-get clean
    - sudo apt-get purge -y ruby mysql-common mysql-client mysql-server postgresql-common postgresql-client postgresql-server-dev-all sqlite3 mongodb-10gen redis-server riak elasticsearch erlang-base libcairo2 libcario2-dev xserver-xorg-core x11-utils x11-common
    - sudo apt-get autoremove
    - sudo rm -rf /usr/share/doc

install:
    - uname -a
    -  df -h
    - sudo add-apt-repository -y ppa:scilifelab/scilifelab
    - sudo add-apt-repository -y ppa:debian-med/ppa
    - sudo apt-get update
    - sudo apt-get install --force-yes git-core gcc picard-tools bowtie bwa freebayes fastqc-0.10.1 gatk r-base texlive texlive-latex-extra tophat openjdk-6-jre samtools unzip lftp cufflinks wigtools
    - df -h
    #TEMPORAL SOLUTION - Install snpEff 2.0.5
    - wget http://sourceforge.net/projects/snpeff/files/snpEff_v2_0_5_core.zip && unzip snpEff_v2_0_5_core.zip && sudo mv snpEff_2_0_5 /usr/share/java/snpeff
    #Download snpeff gnome database
    - lftp -e 'pget -n 8 http://downloads.sourceforge.net/project/snpeff/databases/v2_0_5/snpEff_v2_0_5_GRCh37.63.zip; quit'
    - sudo unzip snpEff_v2_0_5_GRCh37.63.zip -d /usr/share/snpEff/ && rm snpEff_v2_0_5_GRCh37.63.zip
    - python deploy_non_root.py install

before_script:
    - source ~/.bashrc
    - workon master
    - cd ~/opt/bcbb/nextgen/tests

script: nosetests -s -v --with-xunit -a standard